DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('person/', include('person.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

person/urls.py
from django.urls import path
from .views import (PersonHomeView, PersonCreateView, PersonListView, 
                    NewPersonBattleListView, PersonLvlListView, PersonDetailView, 
                    PersonUpdateView, PersonDeleteView)

from . import views

app_name = 'person'

urlpatterns = [
    #path('', views.simple_view),
    path('', PersonHomeView.as_view(), name='home'),
    path('person_create/', PersonCreateView.as_view(), name='create_person'),
    path('person_list/', PersonListView.as_view(), name='list_person'),
    path('person_list_battle/', NewPersonBattleListView.as_view(), name='battle_list_person'),
    path('person_list/lvl/', PersonLvlListView.as_view(), name='lvl_list_person'),
    path('person_detail/<int:pk>', PersonDetailView.as_view(), name='detail_person'),
    path('person_update/<int:pk>', PersonUpdateView.as_view(), name='update_person'),
    path('person_delete/<int:pk>', PersonDeleteView.as_view(), name='delete_person'),
    path('signup/', views.SignUpView.as_view(), name='signup')


]

person/models.py
from urllib import request
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Person(models.Model):
    image = models.URLField(default='https://d1vzi28wh99zvq.cloudfront.net/images/8957/298771.png', blank=True)

    caste = models.CharField(max_length=100, blank=True)

    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)

    team_role = models.CharField(max_length=250, blank=True)
    
    weapon = models.CharField(max_length=250, blank=True)
    shield = models.CharField(max_length=250, blank=True)
    
    outfit = models.CharField(max_length=250, blank=True)
    armor = models.CharField(max_length=250, blank=True)




    lvl = models.IntegerField(default=0, blank=True, null=True)
    xp = models.IntegerField(default=0, blank=True, null=True)
    ac = models.IntegerField(default=10, blank=True, null=True)
    hp = models.IntegerField(default=4, blank=True, null=True)
    speed = models.IntegerField(default=30, blank=True, null=True)



    str = models.IntegerField(default=10, blank=True, null=True)
    dex = models.IntegerField(default=10, blank=True, null=True)
    con = models.IntegerField(default=10, blank=True, null=True)
    int = models.IntegerField(default=10, blank=True, null=True)
    wis = models.IntegerField(default=10, blank=True, null=True)
    cha = models.IntegerField(default=10, blank=True, null=True)

    passive_perception = models.IntegerField(default=10, blank=True, null=True)

    languages = models.CharField(max_length=250, blank=True)
 
    description = models.TextField(blank=True, null=True)
    inventory = models.TextField(blank=True, null=True)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    



    def __str__(self):
        return f"{self.first_name} is equpped with a {self.weapon} and wears {self.armor}."

person/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
#############################################
from django.http import HttpResponse


from urllib import request
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView

from .models import Person
from django.shortcuts import get_object_or_404

from django.db.models import F
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect

from . import models

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.forms import UserCreationForm

from django import forms
# Create your views here.
def simple_view(request):
    return HttpResponse('Hello!')

class PersonHomeView(TemplateView):
    template_name = 'person/home.html'

class PersonCreateView(CreateView):
    model = Person
    # model_form.html --> teacher_form.html
    fields = '__all__'
    success_url = reverse_lazy('person:list_person')

    def form_valid(self, form):     # Alles hier drin ist dafür verantwortlich, 
        obj = form.save(commit=False)   # dass ein sklave automatisch einen owner bekommt.
        obj.owner = self.request.user
        obj.save
        return super().form_valid(form)

class PersonListView(LoginRequiredMixin, ListView):
    model = Person
    context_object_name = "list_of_person"
    queryset = Person.objects.order_by("first_name")


    def get_queryset(self):
        return Person.objects.filter(owner=self.request.user)


class NewPersonBattleListView(LoginRequiredMixin, ListView):
    model = Person
    context_object_name = "list_of_person"
    queryset = Person.objects.order_by("first_name")
    template_name = 'person/person_list_battlex.html'

    def get_queryset(self):
        return Person.objects.filter(owner=self.request.user)


class PersonLvlListView(ListView):
    model = Person
    context_object_name = "list_of_person"
    queryset = Person.objects.order_by("lvl").reverse()


#### Hier hin kommen funktion von den zeilen 87 und 120.


class PersonDetailView(DetailView):
    # model_detail.html
    model = Person


class PersonUpdateView(UpdateView, forms.ModelForm):
    # SHARES model_form.html THAT CREATE VIEW USES
    model = Person
    fields = ['image', 'caste', 'first_name', 'last_name', 'team_role', 'weapon', 'shield', 'outfit', 'armor', 
                'lvl', 'xp', 'ac', 'hp', 'speed', 
                'str', 'dex', 'con', 'int', 'wis', 'cha',
                'passive_perception', 'languages', 'description', 'inventory'] # not included: 'owner'
    widgets = {'owner': forms.HiddenInput()}
    success_url = reverse_lazy('person:list_person')

class PersonDeleteView(DeleteView):
    model = Person
    success_url = reverse_lazy('person:list_person')




class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'person/signup.html'

person/templates/person/home.html
{% extends "base.html" %}
{% block content %}


<h1>DnD Helper Home</h1>

<p>
    TemplateView    DONE
</p>
<p>
    FormView    kinda covered by CreateView
</p>
<p>
    CreateView    DONE
</p>
<a href="{% url 'person:create_person' %}">Create Person</a>
<p>
    ListView
</p>
<a href="{% url 'person:list_person' %}">List Person(s)</a>
<p>
    BattleListView
</p>
<a href="{% url 'person:battle_list_person' %}">Battle List Person(s)</a>
<p>
    DetailView    DONE
</p>
<p>
    UpdateView
</p>
<p>
    DeleteView
</p>



{% if user.is_authenticated %}
    <p>Welcome: {{user.get_username}}</p>
    <a href="{% url 'logout' %}?next={{request.path}}">Logout Here</a>
{% else %}
    <p>You are NOT logged in.</p>
    <p><a href="{% url 'login' %}?next={{request.path}}">Login Here</a></p>
    <p><a href="{% url 'person:signup' %}?next={{request.path}}">Sign Up Here</a></p>
{% endif %}















{% endblock content %}

person/templates/person/person_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<div style="  
margin: auto;
width: 100%;
height: 100%;
padding: 10px;
text-align: center;
background-image: url('https://ze-robot.com/images/source/34688.jpg');
">





    <h1>{{person.first_name}}</h1>

    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm DELETE">
    </form>


</div>

{% endblock %}

person/templates/person/person_detail.html
{% extends "base.html" %}
{% block content %}


<h1 style="text-align: center;">{{person.caste}} {{person.first_name}} {{person.last_name}}</h1>


<div style="display: flex; margin: 1rem; flex-wrap: wrap; justify-content: center;">

    <!-- The image box -->
    <div class="card" style="width: 18rem; margin: 3px; min-width: 200px;">
        <img src="{{person.image}}" class="card-img-top" alt="...">
        <div class="card-body"  style="background-color: rgb(218, 192, 129);">
            <a href="/person/person_update/{{person.id}}" class="card-link">Update</a>
            <a href="/person/person_delete/{{person.id}}" class="card-link">Delete</a>
        </div>
    </div>


    <!-- The overview box -->
    <div class="card" style="width: 18rem; margin: 3px; min-width: 200px;">
        <div class="card-body" style="background-color: rgb(184, 163, 114);">
            <h5 class="card-title"><b>Overview</b></h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>First Name: </b>{{person.first_name}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Last Name: </b> {{person.last_name}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Klasse: </b>    {{person.caste}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Team Role: </b> {{person.team_role}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Weapons: </b>   {{person.weapon}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Shield: </b>    {{person.shield}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Outfit: </b>    {{person.outfit}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Armor: </b>     {{person.armor}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Languages: </b> {{person.languages}}</li>

            
            
        </ul>
    </div>
    
    
    <!-- The stats box -->
    <div class="card" style="width: 18rem; margin: 3px; min-width: 200px;">
        <div class="card-body" style="background-color: rgb(184, 163, 114);">
            <h5 class="card-title"><b>Statistics</b></h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Str: </b>       {{person.str}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Dex: </b>       {{person.dex}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Con: </b>       {{person.con}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Int: </b>       {{person.int}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Wis: </b>       {{person.wis}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Cha: </b>       {{person.cha}}</li>
            
            <li class="list-group-item" style="background-color: rgb(184, 163, 114);"></li>

            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Level: </b>     {{person.lvl}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>XP: </b>        {{person.xp}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>AC: </b>        {{person.ac}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>HP: </b>        {{person.hp}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Speed: </b>     {{person.speed}}</li>
            <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Passive Perception: </b>        {{person.passive_perception}}</li>
</ul>
    </div>

    <!-- The description and inventory box -->
    <div class="card" style="width: 18rem; margin: 3px; min-width: 200px;">
        <div class="card-body" style="background-color: rgb(218, 192, 129);">
            <h5 class="card-title"><b>Description:</b></h5>
            <p class="card-text">{{person.description}}</p>
        </div>

        <ul class="list-group list-group-flush">
            <li class="list-group-item" style="background-color: rgb(184, 163, 114);"></li>
        </ul>

        <div class="card-body" style="background-color: rgb(218, 192, 129);">
            <h5 class="card-title"><b>Inventory:</b></h5>
            <p class="card-text">{{person.inventory}}</p>
        </div>
    </div>


</div>
{% endblock content %}

person/templates/person/person_list.html
{% extends "base.html" %}
{% block content %}


<div style="background-image: url('https://c-rpg.net/img/bg.jpg');">

    <h1 style="text-align: center; color: rgb(94, 11, 11)">List of People</h1>

    <a href="{% url 'person:list_person' %}" class="card-link" ><button type="button" class="btn btn-light">Alphabetical</button></a>
    <a href="{% url 'person:battle_list_person' %}" class="card-link" ><button type="button" class="btn btn-light">Lvl</button></a>

    
    <div style="display: flex; margin: 1rem; flex-wrap: wrap;">
        {% for person in list_of_person %}
        
        
        <div class="card" style="width: 18rem; margin: 3px; min-width: 200px; background-color: rgb(218, 192, 129);">
            <!-- <img src="https://d1vzi28wh99zvq.cloudfront.net/images/8957/298771.png" class="card-img-top" alt="..."> -->
            <div class="card-body">
                <h5 class="card-title">{{person.caste}} {{person.first_name}}</h5>
            </div>
            <ul class="list-group list-group-flush" style="background-color: rgb(218, 192, 129);">
                    <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Team Role:</b> {{person.team_role}}</li>
                    <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Weapons:</b>   {{person.weapon}}</li>
                    <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Shield:</b>    {{person.shield}}</li>
                    <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Armor:</b>     {{person.armor}}    <b>AC:</b> {{person.ac}}</li>
                    

                    
                       
                </ul>
                <div class="card-body">
                    <a href="/person/person_detail/{{person.id}}" class="card-link" ><button type="button" class="btn btn-info">Details</button></a>
                    <a href="/person/person_update/{{person.id}}" class="card-link">Update</a>
                    <a href="/person/person_delete/{{person.id}}" class="card-link"><button type="button" class="btn btn-danger">Delete</button></a>

                </div>
            </div>
            {% endfor %}
    </div>

</div>
{% endblock content %}

person/templates/person/person_list_battlex.html
{% extends "base.html" %}
{% block content %}



<div style="background-image: url('https://c-rpg.net/img/bg.jpg');">

    <h1 style="text-align: center; color: rgb(94, 11, 11)">Battle List</h1>

    <a href="{% url 'person:list_person' %}" class="card-link" ><button type="button" class="btn btn-light">Alphabetical</button></a>
    <a href="{% url 'person:battle_list_person' %}" class="card-link" ><button type="button" class="btn btn-light">Lvl</button></a>

    
    <div style="display: flex; margin: 1rem; flex-wrap: wrap;">

        {% for person in list_of_person %}


        <div class="card" style="width: 18rem; margin: 3px; min-width: 200px; background-color: rgb(218, 192, 129);">
            <!-- <img src="https://d1vzi28wh99zvq.cloudfront.net/images/8957/298771.png" class="card-img-top" alt="..."> -->
            <div class="card-body">
                <h5 class="card-title">{{person.caste}} {{person.first_name}}</h5>
            </div>

            <!-- 1 -->
            <ul class="list-group list-group-flush" style="background-color: rgb(218, 192, 129);">
                <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Weapons:</b>   {{person.weapon}}</li>
                <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Shield:</b>    {{person.shield}}</li>
                <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>AC:</b>     {{person.ac}}<b>Armor:</b>     {{person.armor}}</li>
                
                <li class="list-group-item" style="background-color: rgb(184, 163, 114);"></li>

                <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Str:</b>{{person.str}}<b>||</b>   <b>Dex:</b>{{person.dex}}<b>||</b>   <b>Con:</b>{{person.con}}</li>
                <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Int:</b>{{person.int}}<b>||</b>   <b>Wis:</b>{{person.wis}}<b>||</b>   <b>Cha:</b>{{person.cha}}</li>

                <li class="list-group-item" style="background-color: rgb(184, 163, 114);"></li>

                <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>Speed:</b>     {{person.speed}}    <b>Passive Perception:</b>{{person.passive_perception}}</li>
                <li class="list-group-item" style="background-color: rgb(218, 192, 129);"><b>HP:</b>        {{person.hp}}</li>
            <!-- 3 -->

                <!-- Hier hin kommen 2 js buttons -->
            <!-- 3 -->
            </ul>
            <!-- 1 -->
            <!-- 2 -->
            <div class="card-body">
                <a href="/person/person_detail/{{person.id}}" class="card-link" ><button type="button" class="btn btn-info">Details</button></a>
                <a href="/person/person_update/{{person.id}}" class="card-link">Update</a>
                <a href="/person/person_delete/{{person.id}}" class="card-link"><button type="button" class="btn btn-danger">Delete</button></a>
            </div>
            <!-- 2 -->
            
        </div>
        {% endfor %}

    </div>

</div>
{% endblock content %}

person/templates/person/signup.html
 
{% extends "base.html" %}
{% block content %}

 
 <h1>Register New User Here</h1>
 <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Signup">
 </form>



 {% endblock content %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DnD Helper</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</head>
<body style="background-image: url('https://c-rpg.net/img/bg.jpg');">
    
  {% block popup %}
  {% endblock %}

    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand text-light" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-light" aria-current="page" href="{% url 'person:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'person:create_person' %}">Add Person</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'person:list_person' %}">List People</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'person:battle_list_person' %}">Battle List People</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="#">New X</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="#">My Party</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
            {% if user.is_authenticated %}
              </li>
              <li class="nav-item">
                <a class="nav-link text-muted">{{user.get_username}}</a>
              </li>
            {% endif %}
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    <div style="background-image: url('https://ze-robot.com/images/source/34688.jpg');">
    {% block content %}

    {% endblock %}
    </div>

      <!-- Footer -->
<footer class="text-center text-lg-start bg-dark text-muted">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->


    
</body>
</html>